apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://db_admin:coi2Luh5G49MERvHZr9YzrVfei1mmWrDg5IOzFKivCCIoA0YkvL7TT9isL9dQuIX@postgres-service:5432/postgres?schema=public"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "db_admin"
  POSTGRES_PASSWORD: "coi2Luh5G49MERvHZr9YzrVfei1mmWrDg5IOzFKivCCIoA0YkvL7TT9isL9dQuIX"
  ADMIN_KEY: "88(<q2(bUyA%{(Ozk8jQE6"
  JWT_ACCESS_TOKEN_SECRET: "YeQItUIq6MJi5wMlLVjNbijZXUhiaUMl"
  JWT_ACCESS_TOKEN_EXPIRATION_MS: "3600000"